repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        exclude: rednotebook/external/.*\.py

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.13.0
    hooks:
      - id: pyupgrade
        exclude: rednotebook/external/.*\.py
